---
- name: yum nginx 
  yum: name=nginx state=latest

- name: copy nginx.conf to dest
  template: src=nginx.conf dest=/etc/nginx/conf.d/
  notify: restart nginx

- name: start nginx
  service: name=nginx state=started
