---
- name: restart kafka
  shell: kill -9 `ps ax | grep -i kafka |grep java|grep -v grep | awk '{ print $1}'`;nohup sh /home/hadoop/apps/kafka_2.12-1.0.0/bin/kafka-server-start.sh /home/hadoop/apps/kafka_2.12-1.0.0/config/server.properties &
